### ISSUE TITLE
If you attach too many files the window doesn't fit

### ISSUE THREAD

**Issue by Robby2023** [Inevio/Mail#5]
After attaching several files into an email I realized I couldn't send it because the window was bigger than my screen:

![espacio](https://cloud.githubusercontent.com/assets/1384919/8875218/d2fa0d40-3217-11e5-8754-3cf1c2f3ee56.PNG)

**Comment by Navas23** [comment]
Fixed here https://github.com/Inevio/Mail/commit/3f3af12f5363a46b9c805a9b522ebfed85438b12
